#!/bin/bash

exec 2>&1

export HOME={{pkg.svc_data_path}}

if [ -f {{pkg.svc_config_path}}/labels ]; then

#	kubectl_dir=`hab pkg path mfdii/kubectl`

	labels=`cat {{pkg.svc_config_path}}/labels`

#	echo ${kubectl_dir}/bin/kubectl label pod --overwrite $POD_NAME $labels
#	${kubectl_dir}/bin/
	kubectl label pod --overwrite $POD_NAME $labels
fi

redis-server {{pkg.svc_config_path}}/redis.config
