#!/bin/bash

exec 2>&1

export HOME={{pkg.svc_data_path}}

if [ -f {{pkg.svc_config_path}}/labels ]; then
	labels=`cat {{pkg.svc_config_path}}/labels`
	kubectl label pod --overwrite $POD_NAME $labels
fi

redis-server {{pkg.svc_config_path}}/redis.config
