apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis-slave
spec:
  ports:
  - port: 6379
    targetPort: "redis-slave"
  selector:
    app: redis
    role: follower
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis-master
spec:
  ports:
  - port: 6379
    targetPort: "redis-master"
  selector:
    app: redis
    role: leader
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 5
  template:
    metadata:
      labels:
       app: redis
    spec:
      containers:
      - name: redis
        image: habitat/k8s-redis:latest
        args:
          - --topology
          - leader
          - --peer
          - habitat-mgmt-supervisor
          - --listen-gossip
          - $(POD_IP)
        env:
          - name: HAB_REDIS
            value: 'protected-mode="no"'
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        ports:
          - name: "redis-server"
            containerPort: 6379


